export const DISPATCH_TABLE_COLUMNS = [
  { key: 'drag', label: '' },
  { key: 'seq', label: '#' },
  { key: 'name', label: 'Name' },
  { key: 'tripDateTime', label: 'Trip Date/Time' },
  { key: 'kind', label: 'Stop' },
  { key: 'spaceType', label: 'Space Type' },
  { key: 'targetTime', label: 'Target Time' },
  { key: 'eta', label: 'ETA' },
  { key: 'status', label: 'Status' },
  { key: 'travel', label: 'Travel' },
  { key: 'arriveDist', label: 'Arrive Dist' },
  { key: 'loadUnload', label: 'Load/Unload' },
  { key: 'fundingSource', label: 'Funding Source' },
  { key: 'phone', label: 'Phone' },
  { key: 'address', label: 'Address' },
  { key: 'actions', label: '' },
] as const
